name: Build-Windows-Desktop

on:
  push:
    branches: [main,test_action]
  pull_request:
    branches: [main,test_action]

env:
  FLUTTER_VERSION: ${{ inputs.flutter_version != '' && inputs.flutter_version || vars.FLUTTER_VERSION || '3.27.4' }}

jobs:
  windows-desktop:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true

      - run: flutter config --enable-windows-desktop

      - name: Build Windows desktop
        working-directory: example
        run: |
          flutter pub get
          flutter build windows --release

      - name: Zip binaries
        working-directory: example
        run: |
          7z a windows-x64.zip ./build/windows/x64/runner/Release/*